version: '3'

services:
  webex-rss:
    image: jeremywillans/webex-rss:latest
    #build: .
    container_name: webex-rss
    environment:
      # REPLACE BELOW WITH PREREQUISITE VARIABLES 
      TOKEN: XXXXX
      FEED_ROOM_ID: XXXXX
      CONSOLE_LEVEL: info # Set Debug for detailed logging
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
